services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: tender
      MB_DB_PASS: tenderpass
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tender
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: tenderpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - metanet1

volumes:
  pgdata:
networks:
  metanet1:
    driver: bridge
