// TypeScript array of Russian regions (federal subjects)

interface RussianRegion {
  id: number;
  name: string;
  nameRu: string;
  type:
    | "republic"
    | "krai"
    | "oblast"
    | "city"
    | "autonomous oblast"
    | "autonomous okrug";
  typeRu:
    | "республика"
    | "край"
    | "область"
    | "город"
    | "автономная область"
    | "автономный округ";
  federalDistrict: string;
  federalDistrictRu: string;
  capital?: string;
}

const russianRegions: RussianRegion[] = [
  {
    id: 1,
    name: "Adygea",
    nameRu: "Адыгея",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Maykop",
  },
  {
    id: 2,
    name: "Altai Republic",
    nameRu: "Алтай",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Gorno-Altaysk",
  },
  {
    id: 3,
    name: "Bashkortostan",
    nameRu: "Башкортостан",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Ufa",
  },
  {
    id: 4,
    name: "Buryatia",
    nameRu: "Бурятия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Ulan-Ude",
  },
  {
    id: 5,
    name: "Dagestan",
    nameRu: "Дагестан",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Makhachkala",
  },
  {
    id: 6,
    name: "Ingushetia",
    nameRu: "Ингушетия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Magas",
  },
  {
    id: 7,
    name: "Kabardino-Balkaria",
    nameRu: "Кабардино-Балкария",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Nalchik",
  },
  {
    id: 8,
    name: "Kalmykia",
    nameRu: "Калмыкия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Elista",
  },
  {
    id: 9,
    name: "Karachay-Cherkessia",
    nameRu: "Карачаево-Черкесия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Cherkessk",
  },
  {
    id: 10,
    name: "Karelia",
    nameRu: "Карелия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Petrozavodsk",
  },
  {
    id: 11,
    name: "Komi",
    nameRu: "Коми",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Syktyvkar",
  },
  {
    id: 12,
    name: "Mari El",
    nameRu: "Марий Эл",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Yoshkar-Ola",
  },
  {
    id: 13,
    name: "Mordovia",
    nameRu: "Мордовия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Saransk",
  },
  {
    id: 14,
    name: "Sakha (Yakutia)",
    nameRu: "Саха (Якутия)",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Yakutsk",
  },
  {
    id: 15,
    name: "North Ossetia-Alania",
    nameRu: "Северная Осетия-Алания",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Vladikavkaz",
  },
  {
    id: 16,
    name: "Tatarstan",
    nameRu: "Татарстан",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Kazan",
  },
  {
    id: 17,
    name: "Tuva",
    nameRu: "Тыва",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Kyzyl",
  },
  {
    id: 18,
    name: "Udmurtia",
    nameRu: "Удмуртия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Izhevsk",
  },
  {
    id: 19,
    name: "Khakassia",
    nameRu: "Хакасия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Abakan",
  },
  {
    id: 20,
    name: "Chechnya",
    nameRu: "Чечня",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Grozny",
  },
  {
    id: 21,
    name: "Chuvashia",
    nameRu: "Чувашия",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Cheboksary",
  },
  {
    id: 22,
    name: "Altai Krai",
    nameRu: "Алтайский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Barnaul",
  },
  {
    id: 23,
    name: "Krasnodar Krai",
    nameRu: "Краснодарский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Krasnodar",
  },
  {
    id: 24,
    name: "Krasnoyarsk Krai",
    nameRu: "Красноярский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Krasnoyarsk",
  },
  {
    id: 25,
    name: "Primorsky Krai",
    nameRu: "Приморский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Vladivostok",
  },
  {
    id: 26,
    name: "Stavropol Krai",
    nameRu: "Ставропольский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "North Caucasian",
    federalDistrictRu: "Северо-Кавказский",
    capital: "Stavropol",
  },
  {
    id: 27,
    name: "Khabarovsk Krai",
    nameRu: "Хабаровский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Khabarovsk",
  },
  {
    id: 28,
    name: "Amur Oblast",
    nameRu: "Амурская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Blagoveshchensk",
  },
  {
    id: 29,
    name: "Arkhangelsk Oblast",
    nameRu: "Архангельская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Arkhangelsk",
  },
  {
    id: 30,
    name: "Astrakhan Oblast",
    nameRu: "Астраханская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Astrakhan",
  },
  {
    id: 31,
    name: "Belgorod Oblast",
    nameRu: "Белгородская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Belgorod",
  },
  {
    id: 32,
    name: "Bryansk Oblast",
    nameRu: "Брянская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Bryansk",
  },
  {
    id: 33,
    name: "Vladimir Oblast",
    nameRu: "Владимирская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Vladimir",
  },
  {
    id: 34,
    name: "Volgograd Oblast",
    nameRu: "Волгоградская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Volgograd",
  },
  {
    id: 35,
    name: "Vologda Oblast",
    nameRu: "Вологодская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Vologda",
  },
  {
    id: 36,
    name: "Voronezh Oblast",
    nameRu: "Воронежская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Voronezh",
  },
  {
    id: 37,
    name: "Ivanovo Oblast",
    nameRu: "Ивановская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Ivanovo",
  },
  {
    id: 38,
    name: "Irkutsk Oblast",
    nameRu: "Иркутская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Irkutsk",
  },
  {
    id: 39,
    name: "Kaliningrad Oblast",
    nameRu: "Калининградская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Kaliningrad",
  },
  {
    id: 40,
    name: "Kaluga Oblast",
    nameRu: "Калужская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Kaluga",
  },
  {
    id: 41,
    name: "Kamchatka Krai",
    nameRu: "Камчатский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Petropavlovsk-Kamchatsky",
  },
  {
    id: 42,
    name: "Kemerovo Oblast",
    nameRu: "Кемеровская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Kemerovo",
  },
  {
    id: 43,
    name: "Kirov Oblast",
    nameRu: "Кировская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Kirov",
  },
  {
    id: 44,
    name: "Kostroma Oblast",
    nameRu: "Костромская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Kostroma",
  },
  {
    id: 45,
    name: "Kurgan Oblast",
    nameRu: "Курганская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Ural",
    federalDistrictRu: "Уральский",
    capital: "Kurgan",
  },
  {
    id: 46,
    name: "Kursk Oblast",
    nameRu: "Курская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Kursk",
  },
  {
    id: 47,
    name: "Leningrad Oblast",
    nameRu: "Ленинградская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Saint Petersburg",
  },
  {
    id: 48,
    name: "Lipetsk Oblast",
    nameRu: "Липецкая область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Lipetsk",
  },
  {
    id: 49,
    name: "Magadan Oblast",
    nameRu: "Магаданская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Magadan",
  },
  {
    id: 50,
    name: "Moscow Oblast",
    nameRu: "Московская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Moscow",
  },
  {
    id: 51,
    name: "Murmansk Oblast",
    nameRu: "Мурманская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Murmansk",
  },
  {
    id: 52,
    name: "Nizhny Novgorod Oblast",
    nameRu: "Нижегородская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Nizhny Novgorod",
  },
  {
    id: 53,
    name: "Novgorod Oblast",
    nameRu: "Новгородская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Veliky Novgorod",
  },
  {
    id: 54,
    name: "Novosibirsk Oblast",
    nameRu: "Новосибирская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Novosibirsk",
  },
  {
    id: 55,
    name: "Omsk Oblast",
    nameRu: "Омская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Omsk",
  },
  {
    id: 56,
    name: "Orenburg Oblast",
    nameRu: "Оренбургская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Orenburg",
  },
  {
    id: 57,
    name: "Oryol Oblast",
    nameRu: "Орловская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Oryol",
  },
  {
    id: 58,
    name: "Penza Oblast",
    nameRu: "Пензенская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Penza",
  },
  {
    id: 59,
    name: "Perm Krai",
    nameRu: "Пермский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Perm",
  },
  {
    id: 60,
    name: "Pskov Oblast",
    nameRu: "Псковская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Pskov",
  },
  {
    id: 61,
    name: "Rostov Oblast",
    nameRu: "Ростовская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Rostov-on-Don",
  },
  {
    id: 62,
    name: "Ryazan Oblast",
    nameRu: "Рязанская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Ryazan",
  },
  {
    id: 63,
    name: "Samara Oblast",
    nameRu: "Самарская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Samara",
  },
  {
    id: 64,
    name: "Saratov Oblast",
    nameRu: "Саратовская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Saratov",
  },
  {
    id: 65,
    name: "Sakhalin Oblast",
    nameRu: "Сахалинская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Yuzhno-Sakhalinsk",
  },
  {
    id: 66,
    name: "Sverdlovsk Oblast",
    nameRu: "Свердловская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Ural",
    federalDistrictRu: "Уральский",
    capital: "Yekaterinburg",
  },
  {
    id: 67,
    name: "Smolensk Oblast",
    nameRu: "Смоленская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Smolensk",
  },
  {
    id: 68,
    name: "Tambov Oblast",
    nameRu: "Тамбовская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Tambov",
  },
  {
    id: 69,
    name: "Tver Oblast",
    nameRu: "Тверская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Tver",
  },
  {
    id: 70,
    name: "Tomsk Oblast",
    nameRu: "Томская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Siberian",
    federalDistrictRu: "Сибирский",
    capital: "Tomsk",
  },
  {
    id: 71,
    name: "Tula Oblast",
    nameRu: "Тульская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Tula",
  },
  {
    id: 72,
    name: "Tyumen Oblast",
    nameRu: "Тюменская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Ural",
    federalDistrictRu: "Уральский",
    capital: "Tyumen",
  },
  {
    id: 73,
    name: "Ulyanovsk Oblast",
    nameRu: "Ульяновская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Volga",
    federalDistrictRu: "Приволжский",
    capital: "Ulyanovsk",
  },
  {
    id: 74,
    name: "Chelyabinsk Oblast",
    nameRu: "Челябинская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Ural",
    federalDistrictRu: "Уральский",
    capital: "Chelyabinsk",
  },
  {
    id: 75,
    name: "Zabaykalsky Krai",
    nameRu: "Забайкальский край",
    type: "krai",
    typeRu: "край",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Chita",
  },
  {
    id: 76,
    name: "Yaroslavl Oblast",
    nameRu: "Ярославская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
    capital: "Yaroslavl",
  },
  {
    id: 77,
    name: "Moscow",
    nameRu: "Москва",
    type: "city",
    typeRu: "город",
    federalDistrict: "Central",
    federalDistrictRu: "Центральный",
  },
  {
    id: 78,
    name: "Saint Petersburg",
    nameRu: "Санкт-Петербург",
    type: "city",
    typeRu: "город",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
  },
  {
    id: 79,
    name: "Jewish Autonomous Oblast",
    nameRu: "Еврейская автономная область",
    type: "autonomous oblast",
    typeRu: "автономная область",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Birobidzhan",
  },
  {
    id: 83,
    name: "Nenets Autonomous Okrug",
    nameRu: "Ненецкий автономный округ",
    type: "autonomous okrug",
    typeRu: "автономный округ",
    federalDistrict: "Northwestern",
    federalDistrictRu: "Северо-Западный",
    capital: "Naryan-Mar",
  },
  {
    id: 86,
    name: "Khanty-Mansi Autonomous Okrug",
    nameRu: "Ханты-Мансийский автономный округ",
    type: "autonomous okrug",
    typeRu: "автономный округ",
    federalDistrict: "Ural",
    federalDistrictRu: "Уральский",
    capital: "Khanty-Mansiysk",
  },
  {
    id: 87,
    name: "Chukotka Autonomous Okrug",
    nameRu: "Чукотский автономный округ",
    type: "autonomous okrug",
    typeRu: "автономный округ",
    federalDistrict: "Far Eastern",
    federalDistrictRu: "Дальневосточный",
    capital: "Anadyr",
  },
  {
    id: 89,
    name: "Yamalo-Nenets Autonomous Okrug",
    nameRu: "Ямало-Ненецкий автономный округ",
    type: "autonomous okrug",
    typeRu: "автономный округ",
    federalDistrict: "Ural",
    federalDistrictRu: "Уральский",
    capital: "Salekhard",
  },
  {
    id: 91,
    name: "Republic of Crimea",
    nameRu: "Республика Крым",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Simferopol",
  },
  {
    id: 92,
    name: "Sevastopol",
    nameRu: "Севастополь",
    type: "city",
    typeRu: "город",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
  },
  {
    id: 93,
    name: "Donetsk People's Republic",
    nameRu: "Донецкая Народная Республика",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Donetsk",
  },
  {
    id: 94,
    name: "Luhansk People's Republic",
    nameRu: "Луганская Народная Республика",
    type: "republic",
    typeRu: "республика",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Luhansk",
  },
  {
    id: 95,
    name: "Zaporizhzhia Oblast",
    nameRu: "Запорожская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Zaporizhzhia",
  },
  {
    id: 96,
    name: "Kherson Oblast",
    nameRu: "Херсонская область",
    type: "oblast",
    typeRu: "область",
    federalDistrict: "Southern",
    federalDistrictRu: "Южный",
    capital: "Kherson",
  },
];
